[package]
authors = ["Jacob Brown <kardeiz@gmail.com>"]
categories = ["web-programming::http-server"]
description = "A RegexSet based path router for Hyper"
keywords = ["hyper", "router", "regexset"]
license = "MIT"
name = "reset-router"
readme = "../README.md"
repository = "https://github.com/kardeiz/reset-router"
version = "0.6.0"

[dependencies]
bitflags = "1.0.4"
debugit = "0.1.2"
failure = "0.1.3"
futures = "0.1.25"
http = "0.1.13"
hyper = "0.12.14"
proc-macro-hack = "0.5.2"
regex = "1.0.6"

[dependencies.reset-router-macros]
path = "../reset-router-macros"
version = "0.6.0"
